FILE_GENERAL = "./data/general.csv"
FILE_IQL = "./data/IQL.csv"
FILE_GLOBAL_CONFIG = "./data/global_config.json"
FILE_PAIRING = "./data/pairing.json"
FILE_CONTEXTS = "./data/contexts.csv"
FILE_PENDING_DATA = "./data/pending-data.csv"
FILE_SUGESSION_WEIGHTAGE = "./data/suggestion_weightage.csv"
FILE_TAGS = "./data/tags.json"

DIR_GROUPINGS = "./data/groupings"
